[app]
name = "Smart Team Manager"
version = "0.1.0"
data_dir = "./data"
log_level = "info"

[team]
name = "Engineering Team"
timezone = "UTC"
working_hours = { start = "09:00", end = "17:00" }
working_days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]

[claude]
# Claude CLI integration (MCP tools managed by Claude CLI internally)
enabled = true


[storage]
data_format = "json"